# JWT Configuration
jwt.secret=parksmart-super-secret-jwt-signing-key-must-be-at-least-256-bits-long
jwt.expiration=86400000

# PostgreSQL Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/AADFinalSmartParking_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configurations
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Hibernate Dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect